### PR TITLE
Fix PKGBUILD

### LINKED ISSUE #34: Obs Background Removal for Ubuntu
i like they added background removal for linux (FOR ARCHLINUX)!
i am using ubuntu plz add support for ubuntu
make it .deb file 
plz
Thanks

### LINKED ISSUE #172: Unable to build from git in Arch Linux
Trying to build current master, and getting errors on building 0rt. The end of the error is here, full log attached.

[385/976] Building CXX object CMakeFiles/onnxruntime_session.dir/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/onnxruntime/core/session/inference_session.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/ci_build/build.py", line 2812, in <module>
    sys.exit(main())
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/ci_build/build.py", line 2727, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/ci_build/build.py", line 1349, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/ci_build/build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/home/ngoonee/.cache/aurutils/sync/obs-backgroundremoval-git/src/obs-backgroundremoval/build/Ort-prefix/src/Ort-build/Release', '--config', 'Release', '--', '-j16']' returned non-zero exit status 1.
make[2]: *** [CMakeFiles/Ort.dir/build.make:89: Ort-prefix/src/Ort-stamp/Ort-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:114: CMakeFiles/Ort.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
[errors.txt](https://github.com/royshil/obs-backgroundremoval/files/10952878/errors.txt)

### LINKED ISSUE #262: Unable to build on Arch
**Describe the bug**
Building from git master on Arch throws an error after OpenCV_Build
[ 72%] Built target OpenCV_Build
make[2]: *** No rule to make target 'OpenCV_Build-prefix/lib/libopencv_imgproc.a', 
needed by 'obs-backgroundremoval.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....

Using the following PKGBUILD (slightly modified from AUR one, just removing unnecessary patches) - the build() function is the 'meat' of it
[PKGBUILD.txt](https://github.com/royshil/obs-backgroundremoval/files/11227747/PKGBUILD.txt)

Attaching the complete build log:-

[errors.txt](https://github.com/royshil/obs-backgroundremoval/files/11227745/errors.txt)

### PR DESCRIPTION
**Pull request by umireon**
Closes #262 
Closes #172
Closes #34

### CODE REVIEW

**Comment by ngoonee** [comment]
On Arch this still results in 

make[2]: *** No rule to make target 'OpenCV_Build-prefix/lib/libopencv_imgproc.a', needed by 'obs-backgroundremoval.so'.  Stop.

**Comment by umireon** [comment]
@ngoonee
I have tested this PKGBUILD on my Arch Linux and the build has ended successfully.
Could you ensure you are using the latest PKGBUILD on this PR and test the build again?
Please attach the full log here if the problem still persists.

**Comment by ngoonee** [comment]
The PKGBUILD I am using is this one (from the PR) - 
[PKGBUILD.txt](https://github.com/royshil/obs-backgroundremoval/files/11283967/PKGBUILD.txt)

The full build log is here - 
[errors.txt](https://github.com/royshil/obs-backgroundremoval/files/11283969/errors.txt)

**Comment by umireon** [comment]
@ngoonee Can you create a completely clean build tree and try to run `makepkg -s`?
And can you tell me what commands you used to create your build?

It seems that OpenCV built shared libraries and this resulted in the file missing error because this plugin expected statically-linking OpenCV libraries.

**Comment by JayceFayne** [comment]
> @ngoonee Can you create a completely clean build tree and try to run `makepkg -s`?
> 
> ```
> git clone https://github.com/royshil/obs-backgroundremoval.git
> git switch umireon.fix-arch-pkgbuild
> cd scripts
> makepkg -s
> ```
> 
> And can you tell me what commands you used to create your build?
> 
> It seems that OpenCV built shared libraries and this resulted in the file missing error because this plugin expected statically-linking OpenCV libraries.

I created a clean checkout and can confirm that the error still persists
```
[ 72%] Completed 'OpenCV_Build'
[ 72%] Built target OpenCV_Build
make[2]: *** No rule to make target 'OpenCV_Build-prefix/lib/libopencv_imgproc.a', needed by 'obs-backgroundremoval.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 81%] Building CXX object CMakeFiles/obs-backgroundremoval.dir/src/plugin-main.cpp.o
[ 90%] Building CXX object CMakeFiles/obs-backgroundremoval.dir/src/background-filter.cpp.o
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/obs-backgroundremoval.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
    ```

**Comment by umireon** [comment]
I have updated the PKGBUILD to use the system OpenCV library and now everything will go fine.
@ngoonee @JayceFayne Can you try this again?

**Comment by umireon** [comment]
I believe #257 must be merged to get this plugin worked on Arch but just building will work by this PR.

**Comment by JayceFayne** [comment]
Can confirm, build passes now! 🎉

**Comment by umireon** [comment]
For now, you can check if the CPU version works by removing libonnxruntime_providers_*.so.

```
sudo rm /usr/lib/obs-plugins/libonnxruntime_providers_*.so
```

**Comment by JayceFayne** [comment]
> I have updated the PKGBUILD to use the system OpenCV library and now everything will go fine. @ngoonee @JayceFayne Can you try this again?

Works fine with the version built from this PKGBUILD
Maybe because I am using the CPU version since I have an AMD GPU?

**Comment by umireon** [comment]
The GPU version is still broken now.

**Comment by royshil** [comment]
> The GPU version is still broken now.

Should we merge this and take of GPU in another PR? @umireon

**Comment by umireon** [comment]
The GPU feature on Linux will be fixed on #257

**Comment by umireon** [comment]
I suppose the remaining problem reported on #257 is an issue of setting up CUDA and not an issue of this plugin.

**Review by royshil — APPROVED** [review]
lgtm

**Pull request merged**
