### PR TITLE
Support OBS 28 on M1 Mac

### PR DESCRIPTION
**Pull request by umireon**
Building this repo on M1 Mac and modifying obs-backgroundremoval-macosx.zip enable this plugin to work on M1 Mac.
I created the binary for M1 Mac.
OBS 28 requires plugins to be stored in the plugin bundle and the plugin bundle needs code sign to work.

https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.4.3-umireon

### CODE REVIEW

**Comment by umireon** [comment]
Related to #109

**Comment by chipsenkbeil** [comment]
@umireon I followed the instructions under your tagged link, got all of the expected dialogs (about clicking okay, going into security to allow, and clicking open), but the filter still doesn't show up under audio/video filters.

This is on an M1 Mac Mini running macOS 12.5. Any idea how else to look troubleshoot why this wouldn't show up?

**Comment by umireon** [comment]
@chipsenkbeil 

Try the following command!

```
brew install opencv onnxruntime
```

**Comment by umireon** [comment]
I don't know how I can create the static binary. Does anybody tell me how I can build the static one?

**Comment by umireon** [comment]
I rebuilt the binary and now it should work without any extra dependencies.

**Comment by ahmadmssm** [comment]
Thanks @umireon, I followed the steps but never got the installation security dialog.

**Comment by umireon** [comment]
@ahmadmssm You need to set Allow apps downloaded from to App Store and identified developers on Security & Privacy.

187913722-cef4ade8-f484-44d0-8f8a-2fd401ec4d3c

If this doesn't solve your problem, post here the log of OBS, which can be gotten by running `/Applications/OBS.app/Contents/MacOS/OBS` on your terminal

**Comment by ahmadmssm** [comment]
Thanks for your answer,

Already didi that.

```
error: Source ID 'background_removal' not found
error: Failed to create source 'Background Removal'!
```

**Comment by umireon** [comment]
@ahmadmssm 

Try the following commands:

```
cd
curl -LO https://github.com/umireon/obs-backgroundremoval/releases/download/v0.4.2-umireon/obs-backgroundremoval-macosx-arm64.zip
rm -rf ~/"Library/Application Support/obs-studio/plugins"
mkdir -p ~/"Library/Application Support/obs-studio/plugins"
unzip obs-backgroundremoval-macosx-arm64.zip -d ~/"Library/Application Support/obs-studio/plugins/"
```

You should get the following output on the terminal:

スクリーンショット 2022-09-06 12 01 16

Please follow the installation instructions: https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.4.2-umireon

Please remove existing Background Removal configuration from your filters and add Background Removal again in video filters.

**Comment by JurajVajdaCQL** [comment]
@umireon thank you. I had to actually uninstall my OBS 28 and download/install OBS 28 for mac silicon. Then it all worked 👍

**Comment by umireon** [comment]
It is worth noting that my distribution requires the Apple Silicon edition of OBS.

**Comment by IMNotMax** [comment]
Works great now, I don't know if it's the new release or the brew install command but on a MacBook Pro M1 pro with OBS 28 I finally don't have my background ;)

**Comment by ahmadmssm** [comment]
@umireon It worked, thanks, and yes it is worth noting that your distribution requires the Apple Silicon edition of OBS 28.

**Comment by YakovlevCoded** [comment]
Thank you dude!

**Comment by dsbudiac** [comment]
@umireon Have you tried installing on Ventura? When I follow your instructions for OBS v28, I never get the security warning. Plugin doesn't appear in the filter list either.

**Comment by umireon** [comment]
@dsbudiac Yes this works on Ventura surely. Please uninstall your OBS installation and reinstall [Apple Silicon OBS](https://cdn-fastly.obsproject.com/downloads/obs-studio-28.1.2-macos-arm64.dmg).
If your installation is Intel one, this won't work.

**Comment by MigrantP** [comment]
@umireon Heya, I tried out version 0.4.4 and got an error about the bundle being damaged. I downloaded 0.4.3 instead and it works.

**Comment by jedahan** [comment]
The binary release seems to work great on my mac - what segmentation model do you recommend?

**Comment by KevinDAdam** [comment]
After installing 0.4.4 which initially seemed to work great on my M1 Mac, OBS started to consume al memory at about 1GB per second till OBS crashed. Restarting several times had the same effect. Removed 0.4.4 and the issue goes away.
Something I've done?

**Comment by umireon** [comment]
@KevinDAdam v0.4.5 was released! Apple Vision implementation has some memory leakage and I had fixed it but this implementation has no advantages to MediaPipe model so I decided to remove Apple Vision feature from my bundle!
Try it again!
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.4.5-umireon

**Comment by umireon** [comment]
@jedahan MediaPipe XD

**Comment by umireon** [comment]
@MigrantP 0.4.4 was based on OBS 29 so that it might not work with OBS 28.
I released v0.4.5 which is based on OBS 28 it should work with your environment.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.4.5-umireon

**Comment by KevinDAdam** [comment]
> @KevinDAdam v0.4.5 was released! Apple Vision implementation has some memory leakage and I had fixed it but this implementation has no advantages to MediaPipe model so I decided to remove Apple Vision feature from my bundle!
> Try it again!
> https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.4.5-umireon

Thanks - installed v0.4.5 and it seems to be working well (for 15 min anyway :) ).
Apple Vision looked amazing on my machine - really clear and steady outline. Shame it has a bug.
Currently using 'Selfie Segmentation' as it seems a little better than 'MediaPipe'.
Thanks!

**Comment by ncclementi** [comment]
Hi folks, I have OBS 29 installed for Apple Silicon. I'm confused about which of all of the releases would be the best to install. Any recommendations?

**Comment by umireon** [comment]
@ncclementi The latest is good. I'm preparing a new version that works on all the platforms.

**Comment by royshil** [comment]
this work is now merged after revamping our CI
closing this PR

**Pull request closed without merging**
