### PR TITLE
Add flatpak build to CI

### PR DESCRIPTION
**Pull request by royshil**

### CODE REVIEW

**Comment by umireon** [comment]
I think flatpak should be buiit on the separate job. Messing Linux deb job is not good.

**Comment by umireon** [comment]
I can work on this. I have the environment to develop the flatpak package.

**Comment by royshil** [comment]
@umireon that's great
i dn't have a linux dev env.. only windows and mac
i think the latest change to the cmake script with shared libraries should enable flatpak pretty easy

**Comment by umireon** [comment]
Main cannot be built on flatpak due to #182

**Comment by umireon** [comment]
My work done 
https://github.com/royshil/obs-backgroundremoval/pull/198

**Pull request closed without merging**
