### PR TITLE
Fix to include libonnxruntime.1.15.1

### LINKED ISSUE #347: 1.0.2: Complains about missing libonnxruntime.so.1.15.1 (1.0.1 works fine) - Xubuntu 22.04 LTS
**Describe the bug**

Plugin is not listed as available, shows failure in OBS' logs.

I am in a fresh XUbuntu 22.04 install, installed OBS via PPA, and then grabbed this library from the latest `.deb` release and installed it

**Log and Crash Report**
```
19:46:32.068: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so->/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so): libonnxruntime.so.1.15.1: cannot open shared object file: No such file or directory
19:46:32.068: 
19:46:32.069: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so->/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so): libonnxruntime.so.1.15.1: cannot open shared object file: No such file or directory
19:46:32.069: 
19:46:32.069: Module '/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so' not loaded
```

**Desktop (please complete the following information):**

 - OS: XUbuntu 22.04 (Fresh Install)
 - Browser: Google Chrome 
 - Plugin Version: v1.0.2
 - OBS Version: 29.1.3

**EDIT - IMPORTANT**: Removing 1.0.2 and installing 1.0.1 worked for me! (I can use 1.0.1 just fine). 

Thanks again for this awesome plugin :heart:

### PR DESCRIPTION
**Pull request by umireon**
Closes #347

### CODE REVIEW

**Review by royshil — COMMENTED** [review]
Can you explain why this is needed?
The two lines you add are exactly the same as the line youve removed below...

**Comment by umireon** [comment]
Onnxruntime_LINK_LIBS must be present before Onnxruntime_INSTALL_LIBS because INSTALL one depends on LINK one.
And it must be present after FetchContent_MakeAvailable because it depends on onnxruntime_SOURCE_DIR and SOURCE one is defined after FetchContent_MakeAvailable.

Is this reasonable?

**Comment by royshil** [comment]
Ok this makes sense

**Review by royshil — APPROVED** [review]
LGTM

**Pull request merged**
