### PR TITLE
Fix openSUSE build

### PR DESCRIPTION
**Pull request by umireon**
```
sudo zypper ar -cfp 90 http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/ packman
sudo zypper dup --from packman --allow-vendor-change
sudo zypper in obs-studio
sudo zypper install -t pattern devel_basis
sudo zypper install zsh cmake Mesa-libGL-devel \
  ffmpeg-6-libavcodes-devel ffmpeg-6-libavdevice-devel ffmpeg-6-libavformat-devel \
  libcurl-devel Mesa-libEGL-devel \
  libpulse-devel libxkbcommon-devel
.github/scripts/build-linux.zsh --skip-deps
```

### CODE REVIEW

**Comment by royshil** [comment]
this is looking good - but can we verify it works on SUSE?

**Comment by umireon** [comment]
I have created an openSUSE instance on GCP. I will try this later.

**Comment by umireon** [comment]
I have confirmed that this change fixes the build on openSUSE!

**Review by royshil — APPROVED** [review]
All set to merge!

**Pull request merged**
