### PR TITLE
Add depth estimation model

### PR DESCRIPTION
**Pull request by royshil**
Adding the TCMonoDepth model for depth estimation along with the "blur focus point" setting to simluate depth of field

### CODE REVIEW

**Comment by umireon** [comment]
@royshil Please format

**Comment by royshil** [comment]
@umireon this is ready for review

**Review by umireon — APPROVED** [review]
Amazing work!

**Comment by royshil** [comment]
@umireon i've fixed the blur to be a "Focal blur", now it works as expected
Can you please check on your end?

**Review by umireon — CHANGES_REQUESTED** [review]
Please fix the indentation in effect files.
Tabs and spaces are mixed but we used only tabs so far.

**Comment by umireon** [comment]
And it does not work with the following error

```
error: effect_setval_inline: invalid param
```

**Comment by royshil** [comment]
@umireon i've fixed the problems, thank you for pointing it out!

**Review by umireon — APPROVED** [review]
LGTM!

**Comment by umireon** [comment]
We can call v1.1.0 for this feature?

**Pull request merged**
