### PR TITLE
Background removal without Chrome Key filter

### PR DESCRIPTION
**Pull request by umireon**
TODO: implement feather, configuration

Possible solution for #101

### CODE REVIEW

**Comment by umireon** [comment]
I suggest that this change would go with v0.6.0.

**Comment by umireon** [comment]
@royshil Could you help me to implement the feather matting with the alpha channel?

**Comment by royshil** [comment]
@umireon sure i can - but this branch is on your repo, so i'd need permissions there to be able to push to it

another option is to land this change, and i'll do the feather on this repo's branch

**Comment by umireon** [comment]
I've moved the branch on royshil/obs-backgroundremoval and opened https://github.com/royshil/obs-backgroundremoval/pull/192 so that you can write to my PR.

**Pull request closed without merging**
