### PR TITLE
An update dialog skelton

### PR DESCRIPTION
**Pull request by umireon**
スクリーンショット 2023-07-01 16 17 11

### CODE REVIEW

**Review by royshil — APPROVED** [review]
i'm loving it
but we shouldn't show this to the users right now
so we can keep it here on `main`, just don't add it to the plugin startup
we will build the version checker and the dialog itself, and then we can add it the startup

**Comment by umireon** [comment]
@royshil Can you create a new topic branch for a version checker? I will merge this into that branch.

**Comment by royshil** [comment]
> @royshil Can you create a new topic branch for a version checker? I will merge this into that branch.

you can certainly merge all of this on `main` for now, but we will connect the plugin startup code in a bit after we bring in the other libcurl part

**Comment by umireon** [comment]
@royshil I have removed the code of this PR from plugin-main.c. Is this what you mean?

**Comment by royshil** [comment]
> @royshil I have removed the code of this PR from plugin-main.c. Is this what you mean?

@umireon yes. we're good now!

**Pull request merged**
