### PR TITLE
Fix symbol not found Providers_GetHost

### PR DESCRIPTION
**Pull request by umireon**

### CODE REVIEW

**Comment by umireon** [comment]
I'm asking for testers on #242

**Comment by grinco** [comment]
Can confirm the symbol error is gone, however video freezes once I switch to tensorrt. I am suspecting that it's due to my local set up - where tensort rt, and cudnn are installed in a miniconda env. Someone with a supported OS must confirm.

**Comment by umireon** [comment]
@grinco Can you attach here the OBS log?

**Comment by umireon** [comment]
@grinco reported that the problem which this PR wants to fix is fixed.

> Can confirm the symbol error is gone

This PR blocks #266 so I'd like to merge this PR and handle remaining problems that @grinco reported on #242.

@royshil Can you approve this PR?

**Review by royshil — APPROVED** [review]
lgtm

**Pull request merged**
